# Generated by Django 3.1.1 on 2021-07-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_populartags'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetovisit',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='populartags',
            name='tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
