# Generated by Django 3.1.1 on 2021-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210726_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='placetovisit',
            name='manual_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
