# Generated by Django 3.1.1 on 2021-07-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210726_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='faq',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
