# Generated by Django 3.2.2 on 2021-08-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_destination_faq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Placetovisit',
            new_name='TravelGuide',
        ),
    ]
