# Generated by Django 3.2.2 on 2021-08-03 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_placetovisit_travelguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 13, 52, 886483)),
            preserve_default=False,
        ),
    ]
