# Generated by Django 3.2.2 on 2021-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_travelguide_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPicksEntryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='uploads/TopPicks/')),
                ('box1_text', models.CharField(blank=True, max_length=200, null=True)),
                ('box1_background', models.ImageField(blank=True, null=True, upload_to='uploads/TopPicks/')),
                ('box1_url', models.URLField(blank=True, null=True)),
                ('box2_text', models.CharField(blank=True, max_length=200, null=True)),
                ('box2_background', models.ImageField(blank=True, null=True, upload_to='uploads/TopPicks/')),
                ('box2_url', models.URLField(blank=True, null=True)),
                ('box3_text', models.CharField(blank=True, max_length=200, null=True)),
                ('box3_background', models.ImageField(blank=True, null=True, upload_to='uploads/TopPicks/')),
                ('box3_url', models.URLField(blank=True, null=True)),
                ('text5', models.CharField(blank=True, max_length=200, null=True)),
                ('text5_image', models.ImageField(blank=True, null=True, upload_to='uploads/TopPicks/')),
                ('text_1', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_1', models.CharField(blank=True, max_length=300, null=True)),
                ('text_2', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_2', models.CharField(blank=True, max_length=300, null=True)),
                ('text_3', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_3', models.CharField(blank=True, max_length=300, null=True)),
                ('text_4', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_4', models.CharField(blank=True, max_length=300, null=True)),
                ('text_5', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_5', models.CharField(blank=True, max_length=300, null=True)),
                ('text_6', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_6', models.CharField(blank=True, max_length=300, null=True)),
                ('text_7', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_7', models.CharField(blank=True, max_length=300, null=True)),
                ('text_8', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_8', models.CharField(blank=True, max_length=300, null=True)),
                ('text_9', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_9', models.CharField(blank=True, max_length=300, null=True)),
                ('text_10', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_10', models.CharField(blank=True, max_length=300, null=True)),
                ('text_11', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_11', models.CharField(blank=True, max_length=300, null=True)),
                ('text_12', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_12', models.CharField(blank=True, max_length=300, null=True)),
                ('text_13', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_13', models.CharField(blank=True, max_length=300, null=True)),
                ('text_14', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_14', models.CharField(blank=True, max_length=300, null=True)),
                ('text_15', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_15', models.CharField(blank=True, max_length=300, null=True)),
                ('text_16', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_16', models.CharField(blank=True, max_length=300, null=True)),
                ('text_17', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_17', models.CharField(blank=True, max_length=300, null=True)),
                ('text_18', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_18', models.CharField(blank=True, max_length=300, null=True)),
                ('text_19', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_19', models.CharField(blank=True, max_length=300, null=True)),
                ('text_20', models.CharField(blank=True, max_length=300, null=True)),
                ('slug_20', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
