# Generated by Django 3.2.2 on 2021-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_toppicksentryform'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppicksentryform',
            name='manual_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
