# Generated by Django 3.2.2 on 2021-08-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('course_name', models.CharField(blank=True, max_length=250, null=True)),
                ('course_category', models.CharField(blank=True, max_length=200, null=True)),
                ('course_duration', models.IntegerField(blank=True, null=True)),
                ('course_dur_type', models.CharField(blank=True, max_length=200, null=True)),
                ('course_level', models.CharField(blank=True, max_length=200, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('course_display_name', models.CharField(blank=True, max_length=300, null=True)),
                ('certification', models.CharField(blank=True, max_length=300, null=True)),
                ('trainer_detail', models.CharField(blank=True, max_length=300, null=True)),
                ('manual_slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('summary', models.CharField(blank=True, max_length=100000, null=True)),
                ('achivement', models.CharField(blank=True, max_length=100000, null=True)),
                ('course_details', models.CharField(blank=True, max_length=100000, null=True)),
                ('inclusion', models.CharField(blank=True, max_length=100000, null=True)),
                ('after_course_next_step', models.CharField(blank=True, max_length=100000, null=True)),
                ('regular_price', models.IntegerField(blank=True, default=0, null=True)),
                ('sale_price', models.IntegerField(blank=True, default=0, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='uploads/course')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/course')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/course')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/course')),
            ],
        ),
    ]
