# Generated by Django 3.2.2 on 2021-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_dur_type',
            field=models.CharField(blank=True, choices=[('hour', 'Hour'), ('day', 'Day')], default='', max_length=200, null=True),
        ),
    ]
