# Generated by Django 3.2.2 on 2021-08-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_course_course_dur_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateItineraryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('day_schedule_heading', models.CharField(blank=True, max_length=600, null=True)),
                ('day_schedule_itinerary', models.TextField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=500, null=True)),
                ('activity_price', models.IntegerField(blank=True, null=True)),
                ('other_transport_name', models.CharField(blank=True, max_length=500, null=True)),
                ('other_transport_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
