# Generated by Django 3.2.2 on 2021-08-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_cityhoteldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, max_length=500, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img')),
                ('cityHotelData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cityhoteldata')),
            ],
        ),
    ]
