# Generated by Django 3.2.2 on 2021-08-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_hotelimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityhoteldata',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img'),
        ),
        migrations.AddField(
            model_name='cityhoteldata',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img'),
        ),
        migrations.AddField(
            model_name='cityhoteldata',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img'),
        ),
        migrations.AddField(
            model_name='cityhoteldata',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img'),
        ),
        migrations.AddField(
            model_name='cityhoteldata',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img'),
        ),
        migrations.AddField(
            model_name='cityhoteldata',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img'),
        ),
        migrations.AddField(
            model_name='cityhoteldata',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/hotel-img'),
        ),
        migrations.DeleteModel(
            name='HotelImages',
        ),
    ]
