# Generated by Django 3.2.2 on 2021-08-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210819_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateitinerarydata',
            name='locations',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='stateitinerarydata',
            name='trip_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stateitinerarydata',
            name='trip_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
