# Generated by Django 3.2.2 on 2021-08-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_itinerarydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelguide',
            name='blog1',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog10',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog11',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog12',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog13',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog14',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog15',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog2',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog3',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog4',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog5',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog6',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog7',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog8',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='blog9',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='travelguide',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=500000, null=True),
        ),
    ]
