# Generated by Django 3.2.2 on 2021-08-24 13:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210823_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerarydata',
            old_name='inclusion',
            new_name='inclusion_exclusion',
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='additional_inclusion',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='end_extra_off',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='extra_price_off',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='hotel_nights_1',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='hotel_nights_2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='hotel_nights_3',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='hotel_nights_4',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='hotel_nights_5',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='itinerary_date_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 24, 13, 31, 13, 825487)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='package_display_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='regular_price',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='itinerarydata',
            name='trip_hightlights',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
