# Generated by Django 3.2.2 on 2021-08-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210824_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerarydata',
            old_name='trip_hightlights',
            new_name='trip_highlights',
        ),
    ]
