# Generated by Django 3.2.2 on 2021-08-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_rename_trip_hightlights_itinerarydata_trip_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarydata',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
