# Generated by Django 3.2.6 on 2021-09-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20210831_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
