# Generated by Django 3.2.6 on 2021-09-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_alter_affiliateuser_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateuser',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=200, null=True),
        ),
    ]
