# Generated by Django 3.2.6 on 2021-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_affiliateuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('rentals_type', models.CharField(max_length=122)),
                ('vehicle_gear_type', models.CharField(max_length=122)),
                ('category', models.CharField(max_length=122)),
                ('brand_name', models.CharField(max_length=122)),
                ('product_name', models.CharField(max_length=122)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads/rentals-img')),
                ('product_image_2', models.ImageField(blank=True, null=True, upload_to='uploads/rentals-img')),
                ('specification_1', models.CharField(max_length=122)),
                ('specification_2', models.CharField(max_length=122)),
                ('specification_3', models.CharField(max_length=122)),
                ('popularity_score', models.CharField(max_length=122)),
                ('delivery_option', models.CharField(max_length=122)),
                ('terms_and_conditions', models.TextField()),
                ('price_1_3', models.CharField(max_length=122)),
                ('price_4_7', models.CharField(max_length=122)),
                ('price_8_15', models.CharField(max_length=122)),
                ('price_16_30', models.CharField(max_length=122)),
            ],
        ),
        migrations.AlterField(
            model_name='affiliateuser',
            name='photo_copy',
            field=models.FileField(blank=True, null=True, upload_to='uploads/affiliate_photo_id'),
        ),
    ]
