# Generated by Django 3.2.6 on 2021-09-30 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20210929_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp',
            name='booking_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
