# Generated by Django 3.2.6 on 2021-10-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_erp_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='aid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='erp',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='AffiliateEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_earned', models.CharField(default='', max_length=50)),
                ('total_price', models.IntegerField(default=0, null=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.affiliateuser')),
            ],
        ),
    ]
