# Generated by Django 3.2.6 on 2021-10-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20211003_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AffiliateEarning',
        ),
    ]
