# Generated by Django 3.2.6 on 2021-10-07 12:24

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_delete_affiliateearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateuser',
            name='aid',
            field=models.PositiveBigIntegerField(blank=True, default=product.models.from_100000, null=True),
        ),
    ]
