# Generated by Django 3.2.6 on 2021-10-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_affiliateuser_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=50000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.affiliateuser')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.CharField(max_length=50, null=True)),
                ('total_price', models.IntegerField(default=0, null=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.affiliateuser')),
            ],
        ),
    ]
