# Generated by Django 3.2.6 on 2021-10-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20211007_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='margin',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
