# Generated by Django 3.2.6 on 2021-10-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_affiliateuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelguide',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AffiliateWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.CharField(blank=True, max_length=2000, null=True)),
                ('payemt_status', models.CharField(blank=True, choices=[('done', 'DONE'), ('notdone', 'NOTDONE')], default='notdone', max_length=200, null=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.affiliateuser')),
            ],
        ),
    ]
