# Generated by Django 3.2.6 on 2021-10-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20211007_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_for_agent',
            field=models.BooleanField(default=False),
        ),
    ]
