# Generated by Django 3.2.6 on 2021-10-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_product_available_for_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkHits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(blank=True, max_length=500000, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=4000, null=True)),
                ('product_link', models.CharField(blank=True, max_length=1000000, null=True)),
            ],
        ),
    ]
