# Generated by Django 3.2.6 on 2021-10-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_linkhits'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelink',
            name='product_link',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='affiliatelink',
            name='product_name',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
