# Generated by Django 3.2.6 on 2021-10-20 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20211018_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliatewithdraw',
            old_name='phone_number',
            new_name='account_number',
        ),
        migrations.RemoveField(
            model_name='affiliatewithdraw',
            name='email',
        ),
        migrations.AddField(
            model_name='affiliatewithdraw',
            name='bank_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='affiliatewithdraw',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='affiliatewithdraw',
            name='ip',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='affiliatewithdraw',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affiliatewithdraw',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
