# Generated by Django 3.2.6 on 2021-10-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_auto_20211020_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateearning',
            name='remain_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
