# Generated by Django 3.2.6 on 2021-10-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_affiliateearning_remain_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateearning',
            name='withdrawlable_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
