# Generated by Django 3.2.6 on 2021-10-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_affiliateearning_withdrawlable_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatewithdraw',
            name='payemt_status',
            field=models.CharField(blank=True, choices=[('pending', 'PANDING'), ('Processed', 'PROCESSED'), ('declined', 'DECLINED')], default='pending', max_length=200, null=True),
        ),
    ]
