# Generated by Django 3.1.1 on 2021-10-29 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_alter_affiliatewithdraw_payemt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('aadhar', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=122)),
                ('gstin', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=12)),
                ('photo_id', models.FileField(upload_to='uploads/agent-photo-id')),
                ('alternate_name', models.CharField(max_length=122)),
                ('alternate_phone', models.CharField(max_length=12)),
                ('bank_name', models.CharField(max_length=122)),
                ('account_number', models.CharField(max_length=122)),
                ('ifsc_code', models.CharField(max_length=122)),
                ('upi_id', models.CharField(max_length=122)),
                ('total_earned', models.CharField(default=0, max_length=122)),
                ('withdrawn_till_date', models.CharField(default=0, max_length=122)),
                ('available_balance', models.CharField(default=0, max_length=122)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_page_url', models.CharField(max_length=122)),
                ('display_page_url', models.CharField(max_length=122)),
                ('full_name', models.CharField(max_length=122)),
                ('rating', models.CharField(max_length=122)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
                ('tags', models.CharField(max_length=10000)),
                ('testimonials', models.CharField(max_length=122)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials')),
            ],
        ),
        migrations.CreateModel(
            name='AgentWithdrawHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=122)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('status', models.CharField(max_length=122)),
                ('ip', models.CharField(max_length=122)),
                ('declaration', models.BooleanField(default=True, max_length=122)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentProductBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=100, null=True)),
                ('guest_name', models.CharField(max_length=122)),
                ('guest_phone', models.CharField(max_length=122)),
                ('guest_other_phone', models.CharField(blank=True, max_length=122, null=True)),
                ('guest_email', models.CharField(blank=True, max_length=122, null=True)),
                ('number_of_guests', models.CharField(max_length=122)),
                ('booking_date', models.DateTimeField(default=datetime.datetime.today)),
                ('service_date', models.DateField()),
                ('product_price', models.CharField(max_length=122)),
                ('total_price', models.CharField(max_length=122)),
                ('margin_earned', models.CharField(max_length=122)),
                ('receipt_send_type', models.CharField(default='Send to mail', max_length=122)),
                ('terms_and_conditions', models.BooleanField(default=False, max_length=122)),
                ('status', models.CharField(blank=True, max_length=122, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.agent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
