# Generated by Django 3.1.1 on 2021-10-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_product_margin_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('package_type', models.CharField(max_length=122)),
                ('package_name', models.CharField(max_length=122)),
                ('service_date', models.CharField(max_length=122)),
                ('package_cost', models.CharField(max_length=122)),
                ('paid_amount', models.CharField(max_length=122)),
            ],
        ),
    ]
