# Generated by Django 3.1.1 on 2021-10-31 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_auto_20211031_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialpayment',
            name='purchase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.purchase'),
            preserve_default=False,
        ),
    ]
