# Generated by Django 3.1.1 on 2021-10-31 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_partialpayment_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partialpayment',
            name='purchase',
        ),
    ]
