# Generated by Django 3.1.1 on 2021-10-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_remove_partialpayment_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialpayment',
            name='status',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
