# Generated by Django 3.1.1 on 2021-10-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_partialpayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialpayment',
            name='service_date',
            field=models.DateField(max_length=122),
        ),
    ]
