# Generated by Django 3.1.1 on 2021-10-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_auto_20211031_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialpayment',
            name='orderId',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
