# Generated by Django 3.1.1 on 2021-10-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_partialpayment_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialpayment',
            name='service_date',
            field=models.DateField(blank=True, max_length=122, null=True),
        ),
    ]
