# Generated by Django 3.1.1 on 2021-10-31 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0060_auto_20211031_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partialpayment',
            name='id',
        ),
        migrations.AlterField(
            model_name='partialpayment',
            name='orderId',
            field=models.CharField(default=0, max_length=122, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
