# Generated by Django 3.1.1 on 2021-10-31 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_auto_20211031_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='partial_pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.partialpayment'),
        ),
    ]
