# Generated by Django 3.1.1 on 2021-11-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_purchase_partial_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='number_of_adults',
            field=models.DateField(blank=True, default=None, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='number_of_child',
            field=models.DateField(blank=True, default=None, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='package_type',
            field=models.CharField(blank=True, default=None, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paidAmount',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='service_date',
            field=models.DateField(blank=True, default=None, max_length=122, null=True),
        ),
    ]
