# Generated by Django 3.1.1 on 2021-11-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_auto_20211107_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='service_date',
            new_name='booking_date',
        ),
    ]
