# Generated by Django 3.1.1 on 2021-11-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_auto_20211111_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='partialpayment',
            name='booking_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='partialpayment',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
